### ISSUE TITLE
tracking (internal and outbound)

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/old-website#5]

**Comment by russellsamora** [comment]
* [x] which section are they choosing story from?
* [x] header join newsletter button click
* [x] which top nav do they click?
* [x] social icon sidebar clicks
* [x] topics sidebar choice
* [x] cta clicks
* [x] archives: did they use a filter
* [x] archives: did they click a tag
* [x] archives: did they use search
